# Generated by Django 4.0.3 on 2022-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_status_suborder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Notpayed', max_length=200),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(default='ordering', max_length=200),
        ),
    ]
