# Generated by Django 4.0.3 on 2022-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_status_alter_suborder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='notpayed', max_length=200),
        ),
    ]
