# Generated by Django 4.0.3 on 2022-03-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['SubOrder']},
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
