# Generated by Django 4.0.3 on 2022-03-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderitem_options_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='notanswered', max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackorder', to='app.order')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
