# Generated by Django 4.0.3 on 2022-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactivate', 'deactivate')], default='active', max_length=200),
        ),
    ]
