# Generated by Django 4.0.3 on 2022-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin'), ('chef', 'chef'), ('captain', 'captain'), ('waiter', 'waiter')], max_length=200),
        ),
    ]
