# Generated by Django 4.0.3 on 2022-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_profile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payed', 'payed'), ('notpayed', 'notpayed')], default='notpayed', max_length=200),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('ordering', 'ordering'), ('sendingtochef', 'sendingtochef'), ('chefaccepting', 'chefaccepting'), ('orderisready', 'orderisready'), ('waiteraccept', 'waiteraccept'), ('waiterserving', 'waiterserving'), ('suborderclosed', 'suborderclosed')], default='ordering', max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(blank=True, choices=[('empty', 'empty'), ('reserved', 'reserved')], max_length=200, null=True),
        ),
    ]
