# Generated by Django 4.0.3 on 2022-03-05 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='Order',
        ),
        migrations.AddField(
            model_name='order',
            name='SubOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordertable', to='app.suborder'),
        ),
    ]
