# Generated by Django 4.0.3 on 2022-03-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_suborder_order_order_suborder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='SubOrder',
        ),
        migrations.AddField(
            model_name='suborder',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborderorder', to='app.order'),
        ),
    ]
