# Generated by Django 4.0.3 on 2022-03-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_order_suborder_suborder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackorder', to='app.order'),
        ),
    ]
